name: simple_lint
description: "A simple lint for flutter that warns you about risky code."
version: 2.0.0
repository: https://github.com/MasahideMori-SimpleAppli/simple_lint

environment:
  sdk: ^3.9.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
